// <auto-generated />
namespace StockControll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addOtherTablesToRegisterShoesAndTags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addOtherTablesToRegisterShoesAndTags));
        
        string IMigrationMetadata.Id
        {
            get { return "202309102328145_addOtherTablesToRegisterShoesAndTags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
